services:
- name: app-https-8443
  protocol: TCP
  tcp_portrange: '8443'
  comment: App custom HTTPS port
- name: TCP-552
  protocol: TCP
  tcp_portrange: '552'
  comment: Custom TCP 552
- name: auto-tcp-800
  protocol: TCP
  comment: Auto-created from Slack request by gyeongrs
  tcp_portrange: '800'
- name: auto-tcp-8443
  protocol: TCP
  comment: Auto-created from Slack policy request by gyeongrs
  tcp_portrange: '8443'
